URL_SERVICE = "https://cnt-2229143a-a71a-4948-a60a-07740afbbef9.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
KITS_PATH = "/api/v1/kits"
